name: Docker Build
description: Build the project using Docker
inputs:
  go-options:
    description: Environment variables for go build
    required: true
    default:
  bin-name:
    description: Name of build binary file
    required: true
    default: app
outputs:
  artifact_path:
    description: Path to the build artifact
runs:
  using: docker
  image: ./Dockerfile
  args:
    - ${{ inputs.go-options }}
    - ${{ inputs.bin-name }}