name: Docker Build
description: Build the project using Docker
inputs:
  bin-name:
    description: Name of build binary file
    required: true
    default: app
  target-os:
    description: OS to target
    required: true
    default: linux
  target-arch:
    description: Architecture to target
    required: true
    default: amd64
outputs:
  artifact_path:
    description: Path to the build artifact
runs:
  using: docker
  image: ./Dockerfile
  args:
    - ${{ inputs.bin-name }}
    - ${{ inputs.target-os }}
    - ${{ inputs.target-arch }}
