on:
  push:
    tags:
    - 'v*'

name: Create release with assets

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set output
        id: get-tag
        run: echo ::set-output name=tag::${GITHUB_REF:11}
      - name: Build linux-amd64
        id: build-linux-amd64
        uses: ./.github/actions/docker-build
        with:
          goarch: amd64
          goos: linux
          bin-name: linux-amd64
      - name: Build linux-arm
        id: build-linux-arm
        uses: ./.github/actions/docker-build
        with:
          goarch: arm
          goos: linux
          bin-name: linux-arm
      - name: Build linux-arm64
        id: build-linux-arm64
        uses: ./.github/actions/docker-build
        with:
          goarch: arm64
          goos: linux
          bin-name: linux-arm64
      - name: Build windows-amd64
        id: build-windows-amd64
        uses: ./.github/actions/docker-build
        with:
          goarch: amd64
          goos: windows
          bin-name: windows-amd64
      - name: Build darwin-amd64
        id: build-darwin-amd64
        uses: ./.github/actions/docker-build
        with:
          goarch: amd64
          goos: darwin
          bin-name: darwin-amd64
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Upload linux-amd64
        id: upload-linux-amd64 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.build-linux-amd64.outputs.artifact_path }}
          asset_name: mqcontrol_${{ steps.get-tag.outputs.tag }}_linux_amd64
          asset_content_type: application/octet-stream
      - name: Upload linux-arm
        id: upload-linux-arm 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.build-linux-arm.outputs.artifact_path }}
          asset_name: mqcontrol_${{ steps.get-tag.outputs.tag }}_linux_arm
          asset_content_type: application/octet-stream
      - name: Upload linux-arm64
        id: upload-linux-arm64 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.build-linux-arm64.outputs.artifact_path }}
          asset_name: mqcontrol_${{ steps.get-tag.outputs.tag }}_linux_arm64
          asset_content_type: application/octet-stream
      - name: Upload windows-amd64
        id: upload-windows-amd64 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.build-windows-amd64.outputs.artifact_path }}
          asset_name: mqcontrol_${{ steps.get-tag.outputs.tag }}_windows_amd64.exe
          asset_content_type: application/octet-stream
      - name: Upload darwin-amd64
        id: upload-darwin-amd64 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.build-darwin-amd64.outputs.artifact_path }}
          asset_name: mqcontrol_${{ steps.get-tag.outputs.tag }}_macos_amd64
          asset_content_type: application/octet-stream