name: Docker push
on:
  push:
    branches:
      - test-docker-push
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set output
        id: get-tag
        run: echo ::set-output name=tag::${GITHUB_REF:11}
      - name: Build and push using Docker
        uses: ./.github/actions/docker-push
        with:
          version: 0.2.0
          docker-repo-token: ${{ secrets.DOCKER_HUB_TOKEN }}

